<title>Edit Albums for <?php echo $user->username;?></title>
<html>
	<head>
		<h1>Edit Albums for <?php echo $user->username;?></h1>
	</head>
	<body>
		<form method="POST">
		<table>
			<tr>
				<th>Albums</th>
				<th>Access</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>
			<?php foreach($albums as $album):?>
			<tr>
				<td><?php echo $album->title;?></td>
				<td><?php echo $album->access;?></td>
				<td><a href=<?php echo $this->url('home') . "album/edit?id=" . $album->albumId;?>>[Edit]</a></td>
				<form method="POST">
				<input type="hidden" name="op" value="delete">
				<input type="hidden" name="albumId" value="<?php echo $album->albumId;?>">
				<td><input type="submit" value="Delete" name="Submit"/></td>
				</form>
			</tr>
			<?php endforeach;?>
			<tr>
				<form method="POST">
				<td>New:<input type="text" style="width: 75px" name="Add"></td>
				<td><input type="radio" name="Access" value="public">Public</td>
				<td><input type="radio" name="Access" value="private">Private</td>
				<input type="hidden" name="op" value="add">
				<td><input type="submit" value="Add" name="Submit"/></td>
				</form>
			</tr>
		</table>
		</form>
	</body>
</html>