	<h1><?php echo $album->username."'s album: ".$album->title;?></h1>
	<table>
		<tr>
		<?php foreach($photos as $photo):?>
				<td><a href=<?php echo $this->url('home') . "pic?id=". $photo->picId;?>><img src="<?php echo $photo->url;?>" alt="some_text" width="300px" height="300px" padding="2"></a></td>
		<?php endforeach;?>
		</tr>
		<tr>
		<?php foreach($photos as $photo):?>
			<td>Date: <?php echo $photo->date;?></td>
		<?php endforeach;?>
		</tr>
		<tr>
		<?php foreach($photos as $photo):?>
			<td>Caption: <?php echo $photo->caption;?></td>
		<?php endforeach;?>
		</tr>

	</table>