<?php 
	if (!$user){
	echo 	"<h1>Welcome to project 2 presented by Ryan, Andy and Dom!</h1>
			 <p>Would you like to join the future of photobook social networking?
			 <a href=".$this->url('user').">Click to create a new user</a></p>";
		foreach($publicAlbums as $other){ echo
		"<h2>".$other[0]->username."'s albums</h2>
		<ul>";		
			foreach($other as $album){ echo
			"<li><a href=".$this->url('album')."?id=".$album->albumId.">".$album->title."</a></li>";
		}
		echo "</ul>";
		}
	}
	else{	
	foreach($publicAlbums as $other){ echo
		"<h2>".$other[0]->username."'s albums</h2>
		<ul>";		
		foreach($other as $album){ echo
			"<li><a href=".$this->url('album')."?id=".$album->albumId.">".$album->title."</a></li>";
		}
		echo "</ul>";
	}
	if($userAlbums){
		echo "<h2>Your Albums</h2><ul>";
		foreach($userAlbums as $album){
			echo "<li><a href=".$this->url('album')."?id=".$album->albumId.">".$album->title."</a></li>";
		}
		echo "</ul>";
	}
	else{
		echo "<br><p>You have no albums. <a href=".$this->url('albums/edit').">Would you like to create one?</a></p>";
	}
}

?>