<?php
$title = 'Login';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
 
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('login'));
$form->prepare();
 
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>
<div style="color:#FF0000">
	<strong><?php echo $this->error;?></strong>
</div>
<p>New User? <a href="user">Sign Up</a></p>
