<div style="text-align:center;">
<div>
<a href=<?php echo $this->url('album') . "?id=" . $photo->albumId; ?>>Back to Album</a>
</div>
<div>
	<a href=<?php echo $this->url('pic') . "?id=" . $prev;?>>Previous</a>
	<a href=<?php echo $this->url('pic') . "?id=" . $photo->picId;?>><img src="<?php echo $photo->url;?>" alt="some_text" width="700px" height="700px" padding="2"></a>
	<a href=<?php echo $this->url('pic') . "?id=" . $next;?>>Next</a>
</div>
</div>
<p>Caption: <?php echo $photo->caption;?></p>
