<p>Edit your user information?</p>
<p>User: <?php echo $user->username; ?></p>
<form action="edit" method="post">
	<input type="hidden" name="username" value="<?php echo $user->username;?>">
	<input type="hidden" name="type" value="edit">
	First Name:<input type="text" name="fname" /><br>
	Last Name:<input type="text" name="lname" /><br>
	
	Email Address:<input type="email" name="emailAddr" /><br>

	Password:<input type="password" id="password" name="password" pattern="(?=.{3,15})(?=^[a-zA-Z0-9_]*$)(?=[A-Za-z].*[0-9]|[0-9].*[A-Za-z]).*$"/><br>
	Confirm Password:<input type="password" id="passwordconf" name="passwordconf"  oninput="check(this)" pattern="(?=.{3,15})(?=^[a-zA-Z0-9_]*$)(?=[A-Za-z].*[0-9]|[0-9].*[A-Za-z]).*$" />
	<script language='javascript' type='text/javascript'>
	function check(input) {
	    if (input.value != document.getElementById('password').value) {
	        input.setCustomValidity('The two passwords must match.');
	    } else {
	        // input is valid -- reset the error message
	        input.setCustomValidity('');
	   }
	}
	</script>

	<br>
	<input type="submit" value="Submit"/><br><br>
</form>

<form action="edit" method="post">
	<input type="hidden" name="username" value="<?php echo $user->username;?>">
	<input type = "hidden" name="type" value="delete">
	Delete user?<input type="submit" value="Delete" name="deleteUser"/>
</form>


